global:
  sendAnonymousUsage: true

# log:
#   level: INFO # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#   format: common # [common, json, logfmt]
#   filePath: /log/traefik.log
# accessLog:
#   format: common # [common, json, logfmt]
#   filePath: /log/access.log

api:
  dashboard: true
  insecure: false

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http: # set default tls settings
      tls:
        certResolver: production

certificatesResolvers:
  staging:
    acme:
      email: ${CERTIFICATE_MAIL}
      storage: /certs/acme-staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: ${CERTIFICATE_MAIL}
      storage: /certs/acme-production.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# -- (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true

providers:
  docker:
    network: web
    exposedByDefault: false
    # tls:
    #   insecureSkipVerify: true
  file:
    directory: /etc/traefik
    watch: true
